# COMP4220: Machine Learning, Spring 2021, Assignment 5
Due: Wednsday, April 7, 11pm

Please submit one pdf file for all questions.

You can type your answer for the first two questions in the below cell of each question using "Markdown" option!

****When turning in assignments after the due date, please clearly specify the number of late hours used.

# P1. What is the fundamental idea behind Support Vector Machines?

The fundamental idea behind SVM's is to be fit the widest possible street between classes (in the form of margins). The SVM struggles to find the optimum compromise between finding the widest street and perfectly separating each of the classes.




# P2. If a Decision Tree is underfitting the training set, is it a good idea to try scaling the input features?

Decision Trees do nor require feature scaling, so it would not fix the underfitting of the training set.





# P3.If you have trained five different models on the exact same training data, and they all achieve 95% precision, is there any chance that you can combine these models to get better results? If so, how? If not, why?

Yes, Learning Ensembles combine multiple predictors to often produce an overall higher accuracy than any one model. What it does is aggregate preditions of all the classifiers and then predicts the class that occurs as the most common prediction between the models.





# Programming assignments (SVM, Decision Tree, Random Forest)

In [ ]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [ ]:
# Importing the dataset
dataset = pd.read_csv('Social_Network_Ads.csv')
X = dataset.iloc[:, [2, 3]].values
y = dataset.iloc[:, 4].values


# P4. Programming assignment(SVM)

# P4.1 Split the dataset into the Training set(%75) and Test set(%25) 
use "train_test_split" from sklearn.model_selection.

Use these variables:(X_train, X_test, y_train, y_test)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, train_size = 0.75) #don't actually have to define test and train size as default is exactly what we want

# P4.2 Apply Feature Scaling method for X_train and X_test
Hint: use StandardScaler.fit_transform(X_train) for "X_train" and use StandardScaler.transform(X_test) for "X_test"




In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test= sc.transform(X_test)

# P4.3 Train the SVM model on the Training set, 
(random_state = 0)

In [ ]:
from sklearn import svm

svm_clf = svm.SVC(kernel='linear', random_state = 0)

svm_clf.fit(X_train, y_train)



SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

# P4.4 Predict the Test set results and show the result


In [ ]:
svm_y_pred = svm_clf.predict(X_test)
svm_y_pred

array([0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0])

# P4.5 Make the Confusion Matrix and show the result

In [ ]:
from sklearn.metrics import confusion_matrix
svm_confusionM = confusion_matrix(y_test, svm_y_pred)
svm_confusionM

array([[54,  4],
       [10, 32]])

# P5. Programming assignment(Decision Tree)

# P5.1 Train the Decision Tree Classification on the Training set,
(criterion = 'entropy', random_state = 0)

In [ ]:
from sklearn.tree import DecisionTreeClassifier

tree_clf = DecisionTreeClassifier(criterion = "entropy", random_state = 0)

tree_clf.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

#  P5.2 Predict the Test set results 

In [ ]:
tree_y_pred = tree_clf.predict(X_test)

# P5.3 Make the Confusion Matrix and show the result

In [ ]:
tree_confusionM = confusion_matrix(y_test, tree_y_pred)
tree_confusionM


array([[52,  6],
       [ 9, 33]])

# P6. Programming assignment(Random Forest)

# P6.1 Train the Random Forest Classification on the Training set, 
(criterion = 'entropy', random_state = 0)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rnd_clf = RandomForestClassifier(criterion = "entropy", random_state = 0)

rnd_clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

#  P6.2 Predict the Test set results 

In [ ]:
rnd_y_pred = rnd_clf.predict(X_test)


# P6.3 Make the Confusion Matrix and show the result

In [ ]:
rnd_confusionM = confusion_matrix(y_test, tree_y_pred)
rnd_confusionM

array([[52,  6],
       [ 9, 33]])

# Train and fine-tune a Decision Tree for the moons dataset by following these steps

# P7.1.  Use make_moons(n_samples=10000, noise=0.4) to generate a moons dataset.

In [ ]:
from sklearn.datasets import make_moons

moons_X, moons_y = make_moons(n_samples = 10000, noise = 0.4)

# P7.2. Use train_test_split() to split the dataset into a training set and a test set.

In [ ]:
moons_X_train, moons_X_test, moons_y_train, moons_y_test = train_test_split(moons_X, moons_y, test_size = 0.25, train_size = 0.75)

# P7.3. Use grid search with cross-validation (with the help of the GridSearchCV class) to find good hyperparameter values for a DecisionTreeClassifier.
#Hint: try various values for max_leaf_nodes.


Train it on the full training set using these hyperparameters, and measure your model’s performance on the test set. You should get roughly 85% to 87% accuracy.

By default, GridSearchCV trains the best model found on the whole training set (you can change this by setting refit=False), so you don't need to do it again.

In [ ]:
from sklearn.model_selection import GridSearchCV
parameters = {'max_leaf_nodes': list(range(2,1000))}
dtc = DecisionTreeClassifier()
clf = GridSearchCV(dtc, parameters, n_jobs=-1)
clf.fit(moons_X_train, moons_y_train)



GridSearchCV(cv=None, error_score=nan,
             estimator=DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort='deprecated',
                                              random_state=None,
                                              splitter='best'),
             iid='deprecated', n_jobs=-1,
             param_grid={'max_leaf_nodes': [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 1

# P7.4. Evaluate the model's accuracy and show the result

In [ ]:
print(clf.best_estimator_)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=4,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')


In [ ]:
clf.score(moons_X_test, moons_y_test) #calculate mean accuray based on test and true labels using method in DecisionTreeClassifier

0.8568